name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild -project 'Numerals.xcodeproj' -scheme 'Numerals' -destination 'platform=iOS Simulator,name=iPhone 8' test
    - name: Build App
      run: xcodebuild -project 'Numerals.xcodeproj' -scheme 'Numerals' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
        echo Add other actions to build,
        echo test, and deploy your project.
